from pyta4j.analysis.criteria.return_over_max_drawdown_criterion import ReturnOverMaxDrawdownCriterion
from pyta4j.analysis.criteria.versus_buy_and_hold_criterion import VersusBuyAndHoldCriterion
from pyta4j.analysis.criteria.number_of_winning_positions_criterion import NumberOfWinningPositionsCriterion
from pyta4j.analysis.criteria.number_of_losing_positions_criterion import NumberOfLosingPositionsCriterion
from pyta4j.analysis.criteria.winning_positions_ratio_criterion import WinningPositionsRatioCriterion
